// letter-data.js
const letterData = {
    A: { word: "Apple", emoji: "🍎", wrongOptions: ["Ball ⚽", "Cat 🐱"] },
    B: { word: "Baby", emoji: "👶", wrongOptions: ["Apple 🍎", "Dog 🐶"] },
    C: { word: "Cat", emoji: "🐱", wrongOptions: ["Apple 🍎", "Ball ⚽"] },
    D: { word: "Dog", emoji: "🐶", wrongOptions: ["Cat 🐱", "Apple 🍎"] },
    E: { word: "Egg", emoji: "🥚", wrongOptions: ["Fish 🐟", "Ball ⚽"] },
    F: { word: "Fish", emoji: "🐟", wrongOptions: ["Egg 🥚", "Cat 🐱"] },
    G: { word: "Girl", emoji: "👧", wrongOptions: ["Boy 👦", "Hat 🧢"] },
    H: { word: "Hat", emoji: "🧢", wrongOptions: ["House 🏠", "Apple 🍎"] },
    I: { word: "Igloo", emoji: "🏔️", wrongOptions: ["Jug 🏺", "Ball ⚽"] },
    J: { word: "Jug", emoji: "🏺", wrongOptions: ["Kite 🪁", "Cat 🐱"] },
    K: { word: "Kite", emoji: "🪁", wrongOptions: ["Lion 🦁", "Apple 🍎"] },
    L: { word: "Lion", emoji: "🦁", wrongOptions: ["Monkey 🐒", "Ball ⚽"] },
    M: { word: "Monkey", emoji: "🐒", wrongOptions: ["Nose 👃", "Cat 🐱"] },
    N: { word: "Nose", emoji: "👃", wrongOptions: ["Orange 🍊", "Apple 🍎"] },
    O: { word: "Orange", emoji: "🍊", wrongOptions: ["Pig 🐷", "Ball ⚽"] },
    P: { word: "Pig", emoji: "🐷", wrongOptions: ["Queen 👑", "Cat 🐱"] },
    Q: { word: "Queen", emoji: "👑", wrongOptions: ["Rain ☔", "Apple 🍎"] },
    R: { word: "Rain", emoji: "☔", wrongOptions: ["Sun ☀️", "Ball ⚽"] },
    S: { word: "Sun", emoji: "☀️", wrongOptions: ["Train 🚂", "Cat 🐱"] },
    T: { word: "Train", emoji: "🚂", wrongOptions: ["Umbrella ☂️", "Apple 🍎"] },
    U: { word: "Umbrella", emoji: "☂️", wrongOptions: ["Van 🚐", "Ball ⚽"] },
    V: { word: "Van", emoji: "🚐", wrongOptions: ["Window 🪟", "Cat 🐱"] },
    W: { word: "Window", emoji: "🪟", wrongOptions: ["X-ray 🩻", "Apple 🍎"] },
    X: { word: "X-ray", emoji: "🩻", wrongOptions: ["Yarn 🧶", "Ball ⚽"] },
    Y: { word: "Yarn", emoji: "🧶", wrongOptions: ["Zebra 🦓", "Cat 🐱"] },
    Z: { word: "Zebra", emoji: "🦓", wrongOptions: ["Apple 🍎", "Ball ⚽"] }
};